# DO NOT MODIFY -- auto-generated by Apache Cordova
source 'https://cdn.cocoapods.org/'
platform :ios, '11.0'
use_frameworks!
target 'ionDriver' do
	project 'ionDriver.xcodeproj'
	pod 'Firebase/Core', '6.33.0'
	pod 'Firebase/Auth', '6.33.0'
	pod 'Firebase/Messaging', '6.33.0'
	pod 'Firebase/Performance', '6.33.0'
	pod 'Firebase/RemoteConfig', '6.33.0'
	pod 'Firebase/InAppMessaging', '6.33.0'
	pod 'FirebaseFirestore', :tag => '6.33.0', :git => 'https://github.com/invertase/firestore-ios-sdk-frameworks.git'
	pod 'Firebase/Crashlytics', '6.33.0'
	pod 'GoogleSignIn', '5.0.2'
	pod 'GoogleTagManager', '7.1.4'
end


post_install do |installer|
     installer.pods_project.targets.each do |target|
         target.build_configurations.each do |config|
            if config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'].to_f < 9.0
              config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
            end
         end
     end
  end